# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# Key hint: "even-valued terms" means we can skip the odd terms if we're clever with our math
# Also note that Python can handle and store integer values up to around 200 million
#___________________________________________________________________________________________
# okayherestheplan
# 1: Set up an algorithm for calculating fibonacci sequence numbers
# 2: Modify it to identify and sum only the even numbers
# 3: Modify it to take an upper limit as a parameter
# example - function(number_here) means "Sum the even-valued fibonacci below number_here's value

